In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Introduction to Pandas Data Structures 

## Series

Series consists of _values_ and _indices_. The latter are by default the numbers 0 to N-1

In [6]:
obj = pd.Series([4,7,-5,3])
obj 

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values

array([ 4,  7, -5,  3])

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2 = pd.Series(obj.values, index = ['d','b','a','c'])
obj2 # takes one the values from obj and puts new indices in place

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['a']

-5

In [13]:
obj2['d'] = 6
obj2[['c','a','d']] # 4 is being replaced by 6

c    3
a   -5
d    6
dtype: int64

lets look at filtering, scalar multiplication, applying math functions and **NumPy array operations**

In [14]:
obj2[obj2>0] # displays only the positive numbers

d    6
b    7
c    3
dtype: int64

In [15]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
'b' in obj2, 'e' in obj2

(True, False)

Now take a dictionary and lets transform it into a Series

In [18]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [31]:
states= ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

the functions **`isnull`** and **`notnull`** are used to detect missing data

In [33]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [35]:
obj3 

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [36]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [37]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [40]:
obj4.name = 'population'
obj4.index.name= 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [41]:
obj4.index=['Bob','Steve','Jeff','Ryan']
obj4

Bob          NaN
Steve    35000.0
Jeff     16000.0
Ryan     71000.0
Name: population, dtype: float64

## DataFrame

In [44]:
data = {'state':['Ohio','Ohio','Ohio', 'Nevada','Nevada'], 'year':[2000,2001,2002,2001,2002],'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = pd.DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [45]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [46]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [48]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [52]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

rows can be retrieved with the indexing field method `ix`

In [53]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [55]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [68]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt'] = val 
frame2

year   state  pop Ohio YN  debt
one    2000    Ohio  1.5    True   NaN
two    2001    Ohio  1.7    True  -1.2
three  2002    Ohio  3.6    True   NaN
four   2001  Nevada  2.4   False  -1.5
five   2002  Nevada  2.9   False  -1.7

Adding one column

In [73]:
frame2['Ohio_YN'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt Ohio_YN
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

Deleting one column 

In [74]:
del frame2['Ohio_YN'] # for some reason pandas doesnt like it when you incorporate spaces in the column names

In [76]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [77]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

Transposing 

In [78]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [79]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [80]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [85]:
pdata={'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pdata

{'Nevada': year
 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64, 'Ohio': year
 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64}

In [86]:
pd.DataFrame(pdata)

Nevada  Ohio
year              
2000     NaN   1.5
2001     2.4   1.7

In [87]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [82]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

## Index Objects

In [93]:
obj = pd.Series(range(3), index=['a','b','c'])
index = obj.index
index[1:], index[1]

(Index(['b', 'c'], dtype='object'), 'b')

In [95]:
index = pd.Index(np.arange(3))
index

Int64Index([0, 1, 2], dtype='int64')

In [96]:
obj2 = pd.Series([1.5,-2.5,0], index=index)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [97]:
obj2.index == index #checks element-wise

array([ True,  True,  True], dtype=bool)

In [98]:
obj2.index is index #compares the whole object

True

In [99]:
'Ohio' in frame3.columns, 2003 in frame3.index

(True, False)

## Essential Functionality

In [100]:
obj = pd.Series([4.5,7.2,-5.3,3.6], index= ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [102]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [104]:
obj2 = obj.reindex(['a','b','c','d','e'], fill_value = 0)
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [107]:
obj3 = pd.Series(['blue','purple','yellow'], index =[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [108]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [109]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [110]:
obj3.reindex(range(6), method = 'bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [113]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index = ['a','c','d'], columns =['Ohio','Texas','California']) 
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

reindexing the indices

In [114]:
frame2 = frame.reindex(['a','b','c','d']) 
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

reindexing the columns

In [115]:
states = ['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

or both in one shot

In [116]:
frame.reindex(index = ['a','b','c','d'], method = 'ffill',  columns = states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [117]:
frame.ix[['a','b','c','d'],states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

## Dropping values from an axis 

In [118]:
obj = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [119]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [120]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [122]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index = ['Ohio','Colorado','Utah','New York'], columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [123]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [124]:
data.drop('two',axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [125]:
data.drop(['two','four'],axis = 1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## Indexing, selection, and filtering 

In [141]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [142]:
print(obj['b'], obj[1])

1.0 1.0


In [143]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [144]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [145]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [146]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [147]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [149]:
obj['b':'c']  = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [153]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index = ['Ohio','Colorado','Utah','New York'], columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [155]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [156]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [157]:
data[data < 5] 

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [160]:
data[data < 5] = 0
data # sets all entries to 0 where data is below 5

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [162]:
data.ix[['Colorado','Utah'],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [163]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [164]:
data.ix[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [166]:
data.ix[data.three > 5]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [167]:
data[data.three > 5] # no difference ? 

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [168]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## Arithmetic and data alignment 

In [170]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a','c','d','e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a','c','e','f','g'])
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [172]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns = list('bcd'), index = ['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
df1 # btw, cool way to set up the columns !

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [173]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [174]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

## Artihmetic methods with fill values 

In [178]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [179]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [180]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [181]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [182]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## Operations between DataFrame and Series

In [184]:
arr = np.arange(12.).reshape((3,4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [185]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [186]:
arr - arr[0] # vector gets substracted from every single row 

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [188]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'), index= ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [190]:
series = frame.ix[0] # picks the first row 
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [191]:
frame -series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [194]:
series2 = pd.Series(range(3), index=['b','e','f'] )
series2

b    0
e    1
f    2
dtype: int64

In [195]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [197]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [198]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function application and mapping 

In [200]:
frame = pd.DataFrame(np.random.randn(4,3), columns = list('bde'), index = ['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    1.399958  0.263370  0.296516
Ohio    0.069309  0.030820  1.401613
Texas   0.968974 -0.245455 -1.051423
Oregon -0.165803 -0.931927 -1.995583

In [201]:
np.abs(frame)

b         d         e
Utah    1.399958  0.263370  0.296516
Ohio    0.069309  0.030820  1.401613
Texas   0.968974  0.245455  1.051423
Oregon  0.165803  0.931927  1.995583

DataFrames have the `apply` method

In [203]:
f = lambda x: x.max() - x.min()
frame.apply(f) # by default, applies it to each column

b    1.565761
d    1.195297
e    3.397197
dtype: float64

In [204]:
frame.apply(f,axis=1) # applies it to each row

Utah      1.136588
Ohio      1.370794
Texas     2.020397
Oregon    1.829781
dtype: float64

**`apply`** need not return a scalar value, but can also return a Series with mulitple values.

In [210]:
def f(x):
    return pd.Series([x.min(),x.max()], index=['min','max']) #list of two elements, indexed with 'min' and 'max'

In [211]:
frame.apply(f) # again, by default, applied to each column one by one

b         d         e
min -0.165803 -0.931927 -1.995583
max  1.399958  0.263370  1.401613

In [212]:
frame.apply(f,axis=1) # applied row-wise if specified

min       max
Utah    0.263370  1.399958
Ohio    0.030820  1.401613
Texas  -1.051423  0.968974
Oregon -1.995583 -0.165803

there is also the method **`applymap`** which applies a function to each element individually

In [214]:
format = lambda x: '%.2f' %x # returns a string
frame.applymap(format)

b      d      e
Utah     1.40   0.26   0.30
Ohio     0.07   0.03   1.40
Texas    0.97  -0.25  -1.05
Oregon  -0.17  -0.93  -2.00

the reason it is called **`applymap`** is because it comes close to the **`map`** method for Series.

In [215]:
frame['e'].map(format)

Utah       0.30
Ohio       1.40
Texas     -1.05
Oregon    -2.00
Name: e, dtype: object

## Sorting and ranking 

In [217]:
obj = pd.Series(range(4), index= ['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [219]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index= ['three','one'], columns = ['d','a','b','c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [220]:
frame.sort_index() # classifies the indices

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [221]:
frame.sort_index(axis=1) # classifies the columns

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [222]:
frame.sort_index(axis=1, ascending=False) # classifies the columns in reverse order 

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [229]:
obj = pd.Series([4,7,-3,2])
obj.sort_values() # sorting by values 

2   -3
3    2
0    4
1    7
dtype: int64

UPDATE: use **`.sort_values`** instead of **`.order`**

lets look at what happens if there are missing values 

In [233]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values() 

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

**`.sort_values() `** puts the missing values at the end

In [226]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [232]:
frame.sort_values(by='b') # sorts the DataFrame by values in column 'b'

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

lets now look at **`rank`** method for Series and DataFrame, which comes very close to **`numpy.argsort`**. It assigns ranks from one through the number of valid data points in an array.

In [234]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank() # huh? whats going on here? p.131

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [235]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [236]:
obj.rank(ascending = False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [238]:
frame = pd.DataFrame({'b':[4.3,7 ,-3,2], 'a': [0,1,0,1], 'c':[-2,5,8,-2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [239]:
frame.rank(axis =1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

## Axis indexes with duplicate values 

**First case**: duplicates for Series

In [240]:
obj = pd.Series(range(5), index= ['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [241]:
obj.index.is_unique # means there are indeed duplicates in the indices

False

In [242]:
obj['a']

a    0
a    1
dtype: int64

In [243]:
obj['c']

4

**Second case**: duplicates for DataFrames

In [245]:
df = pd.DataFrame(np.random.randn(4,3),index= ['a','a','b','b'])
df

0         1         2
a  1.433533 -0.812842  1.805003
a  1.077114 -0.689646  0.413690
b -0.328150  0.417169  2.441920
b -0.314058 -0.472725  1.259463

In [246]:
df.ix['b']

0         1         2
b -0.328150  0.417169  2.441920
b -0.314058 -0.472725  1.259463

## Summarizing and Computing Descriptive Statistics  

Pandas has a couple of methods that deliver summary statistics of the DataFrame entries 

In [249]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]], index= list('abcd'), columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

**`.sum()`** method 

In [250]:
df.sum(axis=1) # sums up the rows, by default one sums up the columns 

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

**`.mean()`** method

In [252]:
df.mean(axis=1,skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [254]:
df.idxmax() # for each columns returns the index that has maximum

one    b
two    d
dtype: object

In [255]:
df.cumsum() # cumsums along the columns

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [258]:
df.describe()

/Users/giancarlokerg/anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py:3823: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%         NaN       NaN
50%         NaN       NaN
75%         NaN       NaN
max    7.100000 -1.300000

In [260]:
obj = pd.Series(['a','a','b','c']*4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [262]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [264]:
obj.describe().ix['unique']

3

## Correlation and Covariance 

import pandas.io.data as web 
all_data = {}
for ticker in ['AAPL','IBM','MSFT','GOOG']:
    all_data[ticker] = web.get_data_yahoo(ticker)

Series has `.corr()` method 

DataFrame has `.corr()` and `.cov()`, as well as `.corrwith()`

## Unique Values, Value Count, and Membership

In [272]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [273]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [275]:
pd.value_counts(obj.values, sort=False)

d    1
a    3
b    2
c    3
dtype: int64

In [277]:
mask = obj.isin(['b','c'])
mask 

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [278]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [286]:
data = pd.DataFrame({'Qu1':[1,3,4,3,'durr'], 'Qu2':['durr',3,1,2,'blurb'], 'Qu3':[1,'bla',2,4,4]})
data

Qu1    Qu2  Qu3
0     1   durr    1
1     3      3  bla
2     4      1    2
3     3      2    4
4  durr  blurb    4

In [287]:
data.apply(pd.value_counts) # row indices are the values of above table, entries = how many of them are there  

Qu1  Qu2  Qu3
3      2.0  1.0  NaN
4      1.0  NaN  2.0
durr   1.0  1.0  NaN
1      1.0  1.0  1.0
blurb  NaN  1.0  NaN
2      NaN  1.0  1.0
bla    NaN  NaN  1.0

In [289]:
data.apply(pd.value_counts).fillna(0) # just to mask out these ugly NaN's

Qu1  Qu2  Qu3
3      2.0  1.0  0.0
4      1.0  0.0  2.0
durr   1.0  1.0  0.0
1      1.0  1.0  1.0
blurb  0.0  1.0  0.0
2      0.0  1.0  1.0
bla    0.0  0.0  1.0

## Handling Missing Data

In [291]:
string_data = pd.Series(['aardvark','artichoke',np.nan,'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [292]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [294]:
string_data[0] = None #just sets 0th entry to None
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [295]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

## Filtering out Missing Data

In [298]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna() # kicks out all the NA's

0    1.0
2    3.5
4    7.0
dtype: float64

In [299]:
data[data.notnull()] # 

0    1.0
2    3.5
4    7.0
dtype: float64

In [301]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [303]:
cleaned = data.dropna() # drops every row that contains NaN
cleaned

0    1    2
0  1.0  6.5  3.0

In [304]:
data.dropna(how = 'all') # only drops rows that has all entries with NaN

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [305]:
data.dropna(axis=1, how = 'all') # only drops columns that has all entries with NaN

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

now lets look at time series data within a DataFrame. Our aim is to keep only rows with a certain number of observations

In [306]:
df = pd.DataFrame(np.random.randn(7,3))
df

0         1         2
0  1.772112  0.024151  2.349892
1 -1.053350  0.348473 -2.512686
2 -0.347611  1.392008 -0.629551
3 -0.959076 -1.112716  0.797717
4  1.058713 -0.776811 -1.384742
5 -0.957178 -0.633871  0.665688
6  0.151431  1.226351  0.320590

lets throw in some NAs

In [308]:
df.ix[:4,1] = NA # for the 2nd column
df.ix[:2,2] = NA # for the 3rd column
df

0         1         2
0  1.772112       NaN       NaN
1 -1.053350       NaN       NaN
2 -0.347611       NaN       NaN
3 -0.959076       NaN  0.797717
4  1.058713       NaN -1.384742
5 -0.957178 -0.633871  0.665688
6  0.151431  1.226351  0.320590

In [309]:
df.dropna(thresh=3) # selects all rows with at least 3 entries

0         1         2
5 -0.957178 -0.633871  0.665688
6  0.151431  1.226351  0.320590

## Filling in Missing Data

In [313]:
df.fillna(0)

0         1         2
0  1.772112  0.000000  0.000000
1 -1.053350  0.000000  0.000000
2 -0.347611  0.000000  0.000000
3 -0.959076  0.000000  0.797717
4  1.058713  0.000000 -1.384742
5 -0.957178 -0.633871  0.665688
6  0.151431  1.226351  0.320590

In [314]:
df.fillna({1: 0.5, 3:-1})

0         1         2
0  1.772112  0.500000       NaN
1 -1.053350  0.500000       NaN
2 -0.347611  0.500000       NaN
3 -0.959076  0.500000  0.797717
4  1.058713  0.500000 -1.384742
5 -0.957178 -0.633871  0.665688
6  0.151431  1.226351  0.320590

In [315]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0  1.772112  0.000000  0.000000
1 -1.053350  0.000000  0.000000
2 -0.347611  0.000000  0.000000
3 -0.959076  0.000000  0.797717
4  1.058713  0.000000 -1.384742
5 -0.957178 -0.633871  0.665688
6  0.151431  1.226351  0.320590

In [318]:
df = pd.DataFrame(np.random.randn(6,3))
df.ix[2:,1]=NA; df.ix[4:,2]=NA
df

0         1         2
0  1.298834 -0.087163  1.312358
1  0.149239  0.915292  2.475227
2  0.978639       NaN -0.582471
3 -0.511484       NaN -0.521963
4 -1.702126       NaN       NaN
5  1.368541       NaN       NaN

In [319]:
df.fillna(method = 'ffill')

0         1         2
0  1.298834 -0.087163  1.312358
1  0.149239  0.915292  2.475227
2  0.978639  0.915292 -0.582471
3 -0.511484  0.915292 -0.521963
4 -1.702126  0.915292 -0.521963
5  1.368541  0.915292 -0.521963

In [320]:
df.fillna(method = 'ffill', limit=2)

0         1         2
0  1.298834 -0.087163  1.312358
1  0.149239  0.915292  2.475227
2  0.978639  0.915292 -0.582471
3 -0.511484  0.915292 -0.521963
4 -1.702126       NaN -0.521963
5  1.368541       NaN -0.521963

In [321]:
data = pd.Series([1.,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# Hierarchical Indexing 

In [322]:
data = pd.Series(np.random.randn(10), index = [['a','a','a','b','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,2,3]])
data

a  1   -0.039803
   2    1.915116
   3    0.596307
b  1   -0.026818
   2    0.415182
   3   -0.398705
c  1   -1.045118
   2    0.300642
d  2   -0.929106
   3   -0.262694
dtype: float64

In [323]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [324]:
data['b']

1   -0.026818
2    0.415182
3   -0.398705
dtype: float64

In [325]:
data['b':'c']

b  1   -0.026818
   2    0.415182
   3   -0.398705
c  1   -1.045118
   2    0.300642
dtype: float64

In [326]:
data.ix[['b','d']]

b  1   -0.026818
   2    0.415182
   3   -0.398705
d  2   -0.929106
   3   -0.262694
dtype: float64

In [327]:
data[:,2]

a    1.915116
b    0.415182
c    0.300642
d   -0.929106
dtype: float64

In [328]:
data.unstack()

1         2         3
a -0.039803  1.915116  0.596307
b -0.026818  0.415182 -0.398705
c -1.045118  0.300642       NaN
d       NaN -0.929106 -0.262694

In [330]:
data.unstack().stack()

a  1   -0.039803
   2    1.915116
   3    0.596307
b  1   -0.026818
   2    0.415182
   3   -0.398705
c  1   -1.045118
   2    0.300642
d  2   -0.929106
   3   -0.262694
dtype: float64

In [333]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), index=[['a','a','b','b'],[1,2,1,2]], columns=[['Ohio','Ohio','Colorado'],['Green','Red','Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [334]:
frame.index.names = ['key1','key2']
frame.columns.names = ['state','color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [335]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [337]:
pd.MultiIndex.from_arrays([['Ohio','Ohio','Colorado'],['Green','Red','Green']], names = ['state','color'])

MultiIndex(levels=[['Colorado', 'Ohio'], ['Green', 'Red']],
           labels=[[1, 1, 0], [0, 1, 0]],
           names=['state', 'color'])

## Reordering and Sorting Levels 

In [338]:
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [341]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [339]:
frame.sortlevel(1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [340]:
frame.swaplevel(0,1).sortlevel(0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

## Summary Statistics by Level

In [344]:
frame.sum(level = 'key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [345]:
frame.sum(level='color', axis= 1)

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

## Using a DataFrame's Columns 

In [346]:
frame = pd.DataFrame({'a':range(7),'b':range(7,0,-1), 'c':['one','one','one','two','two','two','two'],'d':[0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [348]:
frame2 = frame.set_index(['c','d'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [349]:
frame.set_index(['c','d'],drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [351]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

# Other Pandas Topics  

## Integer Indexing 

In [353]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [355]:
# ser[-1] throws error
ser2 = pd.Series(np.arange(3.), index= ['a','b','c'])
ser2[-1] # here it works

2.0

In [356]:
ser.ix[:1]

0    0.0
1    1.0
dtype: float64

In [362]:
ser3 = pd.Series(range(3), index = [-5,1,3])
ser3.iget_value(2)

/Users/giancarlokerg/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: FutureWarning: iget_value(i) is deprecated. Please use .iloc[i] or .iat[i]
  from ipykernel import kernelapp as app


2

In [363]:
frame = pd.DataFrame(np.arange(6).reshape(3,2), index = [2,0,1])
frame.irow(0)

/Users/giancarlokerg/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: FutureWarning: irow(i) is deprecated. Please use .iloc[i]
  from ipykernel import kernelapp as app


0    0
1    1
Name: 2, dtype: int64

## Panel Data 

three-dimensional analogue of DataFrame